modules = {
	'cd0184':	['Distortion', 'Kinky Boost (mono)'],
	'cd0185':	['Distortion', 'Kinky Boost (stereo)'],
	'cd01fe':	['Distortion', 'Deranged Master (mono)'],
	'cd01ff':	['Distortion', 'Deranged Master (stereo)'],
	'64':	['Distortion', 'Minotaur (mono)'],
	'70':	['Distortion', 'Minotaur (stereo)'],
	'cd012e':	['Distortion', 'Teemah! (mono)'],
	'cd012f':	['Distortion', 'Teemah! (stereo)'],
	'cd0223':	['Distortion', 'Heir Apparent (mono)'],
	'cd0224':	['Distortion', 'Heir Apparent (stereo)'],
	'cd0225':	['Distortion', 'Tone Sovereign (mono)'],
	'cd0226':	['Distortion', 'Tone Sovereign (stereo)'],
	'cd0229':	['Distortion', 'Alpaca Rogue (mono)'],
	'cd022a':	['Distortion', 'Alpaca Rogue (stereo)'],
	'60':	['Distortion', 'Compulsive Drive (mono)'],
	'6c':	['Distortion', 'Compulsive Drive (stereo)'],
	'cd020d':	['Distortion', 'Dhyana Drive (mono)'],
	'cd020e':	['Distortion', 'Dhyana Drive (stereo)'],
	'cd0246':	['Distortion', 'Horizon Drive (mono)'],
	'cd0247':	['Distortion', 'Horizon Drive (stereo)'],
	'69':	['Distortion', 'Valve Driver (mono)'],
	'75':	['Distortion', 'Valve Driver (stereo)'],
	'66':	['Distortion', 'Top Secret OD (mono)'],
	'72':	['Distortion', 'Top Secret OD (stereo)'],
	'65':	['Distortion', 'Scream 808 (mono)'],
	'71':	['Distortion', 'Scream 808 (stereo)'],
	'61':	['Distortion', 'Hedgehog D9 (mono)'],
	'6d':	['Distortion', 'Hedgehog D9 (stereo)'],
	'cd0154':	['Distortion', 'Stupor OD (mono)'],
	'cd0155':	['Distortion', 'Stupor OD (stereo)'],
	'cd01fc':	['Distortion', 'Deez One Vintage (mono)'],
	'cd01fd':	['Distortion', 'Deez One Vintage (stereo)'],
	'cd01fa':	['Distortion', 'Deez One Mod (mono)'],
	'cd01fb':	['Distortion', 'Deez One Mod (stereo)'],
	'6a':	['Distortion', 'Vermin Dist Mono, Stereo Pro Co RAT (mono)'],
	'76':	['Distortion', 'Vermin Dist Mono, Stereo Pro Co RAT (stereo)'],
	'cd0120':	['Distortion', 'KWB Mono, Stereo Benadrian Kowloon Walled Bunny Distortion (mono)'],
	'cd0121':	['Distortion', 'KWB Mono, Stereo Benadrian Kowloon Walled Bunny Distortion (stereo)'],
	'cd0234':	['Distortion', 'Legendary Drive Mono, Stereo Carvin VLD1 Legacy Drive (hi gain channel) (mono)'],
	'cd0235':	['Distortion', 'Legendary Drive Mono, Stereo Carvin VLD1 Legacy Drive (hi gain channel) (stereo)'],
	'cd0248':	['Distortion', 'Swedish Chainsaw Mono, Stereo Boss HM-2 Heavy Metal Distortion (MIJ) (mono)'],
	'cd0249':	['Distortion', 'Swedish Chainsaw Mono, Stereo Boss HM-2 Heavy Metal Distortion (MIJ) (stereo)'],
	'5f':	['Distortion', 'Arbitrator Fuzz Mono, Stereo Arbiter FuzzFace (mono)'],
	'6b':	['Distortion', 'Arbitrator Fuzz Mono, Stereo Arbiter FuzzFace (stereo)'],
	'cd0253':	['Distortion', 'Pocket Fuzz Mono, Stereo Jordan Boss Tone Fuzz (mono)'],
	'cd0254':	['Distortion', 'Pocket Fuzz Mono, Stereo Jordan Boss Tone Fuzz (stereo)'],
	'cd0236':	['Distortion', 'Bighorn Fuzz Mono, Stereo 73 Electro-Harmonix RamGerman Ubersonic Guitar Bogner Ueberschall  (mono)s Head Big Muff Pi (mono)'],
	'cd0237':	['Distortion', 'Bighorn Fuzz Mono, Stereo 73 Electro-Harmonix Rams Head Big Muff Pi (stereo)'],
	'67':	['Distortion', 'Triangle Fuzz Mono, Stereo Electro-Harmonix Big Muff Pi (mono)'],
	'73':	['Distortion', 'Triangle Fuzz Mono, Stereo Electro-Harmonix Big Muff Pi (stereo)'],
	'cd0251':	['Distortion', 'Ballistic Fuzz Mono, Stereo Euthymia ICBM Fuzz (mono)'],
	'cd0252':	['Distortion', 'Ballistic Fuzz Mono, Stereo Euthymia ICBM Fuzz (stereo)'],
	'62':	['Distortion', 'Industrial Fuzz Mono, Stereo Z.Vex Fuzz Factory (mono)'],
	'6e':	['Distortion', 'Industrial Fuzz Mono, Stereo Z.Vex Fuzz Factory (stereo)'],
	'68':	['Distortion', 'Tycoctavia Fuzz Mono, Stereo Tycobrahe Octavia (mono)'],
	'74':	['Distortion', 'Tycoctavia Fuzz Mono, Stereo Tycobrahe Octavia (stereo)'],
	'cd0140':	['Distortion', 'Wringer Fuzz Mono, Stereo Garbages modded BOSS FZ-2 (mono)'],
	'cd0141':	['Distortion', 'Wringer Fuzz Mono, Stereo Garbages modded BOSS FZ-2 (stereo)'],
	'cd0182':	['Distortion', 'Thrifter Fuzz Mono, Stereo Line 6 Original (mono)'],
	'cd0183':	['Distortion', 'Thrifter Fuzz Mono, Stereo Line 6 Original (stereo)'],
	'cd022b':	['Distortion', 'Xenomorph Fuzz Mono, Stereo Subdecay Harmonic Antagonizer (mono)'],
	'cd022c':	['Distortion', 'Xenomorph Fuzz Mono, Stereo Subdecay Harmonic Antagonizer (stereo)'],
	'63':	['Distortion', 'Megaphone Mono, Stereo Megaphone (mono)'],
	'6f':	['Distortion', 'Megaphone Mono, Stereo Megaphone (stereo)'],
	'cd0122':	['Distortion', 'Bitcrusher Mono, Stereo Line 6 Original (mono)'],
	'cd0123':	['Distortion', 'Bitcrusher Mono, Stereo Line 6 Original (stereo)'],
	'cd0209':	['Distortion', 'Ampeg Scrambler Mono, Stereo Ampeg Scrambler Bass Overdrive (mono)'],
	'cd020a':	['Distortion', 'Ampeg Scrambler Mono, Stereo Ampeg Scrambler Bass Overdrive (stereo)'],
	'cd020b':	['Distortion', 'ZeroAmp Bass DI Mono, Stereo Tech 21 SansAmp Bass Driver DI V1 (mono)'],
	'cd020c':	['Distortion', 'ZeroAmp Bass DI Mono, Stereo Tech 21 SansAmp Bass Driver DI V1 (stereo)'],
	'cd015f':	['Distortion', 'Obsidian 7000 Mono, Stereo Darkglass Electronics Microtubes B7K Ultra (mono)'],
	'cd0160':	['Distortion', 'Obsidian 7000 Mono, Stereo Darkglass Electronics Microtubes B7K Ultra (stereo)'],
	'cd01b2':	['Distortion', 'Tube Drive Legacy Chandler Tube Driver (legacy)'],
	'cd01af':	['Distortion', 'Screamer Legacy Ibanez Tube Screamer (legacy)'],
	'cd01ad':	['Distortion', 'Overdrive Legacy DOD Overdrive/Preamp 250 (legacy)'],
	'cd01a3':	['Distortion', 'Classic Dist Legacy ProCo RAT (legacy)'],
	'cd01a7':	['Distortion', 'Heavy Dist Legacy BOSS Metal Zone (legacy)'],
	'cd01a4':	['Distortion', 'Colordrive Legacy Colorsound Overdriver (legacy)'],
	'cd01a2':	['Distortion', 'Buzz Saw Legacy Maestro Fuzz Tone (legacy)'],
	'cd01a5':	['Distortion', 'Facial Fuzz Legacy Arbiter Fuzz Face (legacy)'],
	'cd01a9':	['Distortion', 'Jumbo Fuzz Legacy Vox Tone Bender (legacy)'],
	'cd01a6':	['Distortion', 'Fuzz Pi (legacy)'],
	'cd01a8':	['Distortion', 'Jet Fuzz (legacy)'],
	'cd01ab':	['Distortion', 'L6 Drive (legacy)'],
	'cd01aa':	['Distortion', 'L6 Distortion (legacy)'],
	'cd01b0':	['Distortion', 'Sub Oct Fuzz (legacy)'],
	'cd01ac':	['Distortion', 'Octave Fuzz (legacy)'],
	'77':	['Dynamic', 'Deluxe Comp (mono)'],
	'7c':	['Dynamic', 'Deluxe Comp (stereo)'],
	'79':	['Dynamic', 'Red Squeeze (mono)'],
	'7e':	['Dynamic', 'Red Squeeze (stereo)'],
	'cd01dc':	['Dynamic', 'Kinky Comp (mono)'],
	'cd01dd':	['Dynamic', 'Kinky Comp (stereo)'],
	'cd022d':	['Dynamic', 'Rochester Comp (mono)'],
	'cd022e':	['Dynamic', 'Rochester Comp (stereo)'],
	'78':	['Dynamic', 'LA Studio Comp (mono)'],
	'7d':	['Dynamic', 'LA Studio Comp (stereo)'],
	'cd016f':	['Dynamic', '3-Band Comp (mono)'],
	'cd0170':	['Dynamic', '3-Band Comp (stereo)'],
	'7b':	['Dynamic', 'Noise Gate (mono)'],
	'cc80':	['Dynamic', 'Noise Gate (stereo)'],
	'7a':	['Dynamic', 'Hard Gate (mono)'],
	'7f':	['Dynamic', 'Hard Gate (stereo)'],
	'cd0255':	['Dynamic', 'Horizon Gate (mono)'],
	'cd0256':	['Dynamic', 'Horizon Gate (stereo)'],
	'cd0169':	['Dynamic', 'Autoswell (mono)'],
	'cd016a':	['Dynamic', 'Autoswell (stereo)'],
	'cc84':	['EQ', 'Simple EQ (mono)'],
	'cc88':	['EQ', 'Simple EQ (stereo)'],
	'cc82':	['EQ', 'Low and High Cut (mono)'],
	'cc86':	['EQ', 'Low and High Cut (stereo)'],
	'cd020f':	['EQ', 'Low/High Shelf (mono)'],
	'cd0210':	['EQ', 'Low/High Shelf (stereo)'],
	'cc83':	['EQ', 'Parametric (mono)'],
	'cc87':	['EQ', 'Parametric (stereo)'],
	'cd0211':	['EQ', 'Tilt (mono)'],
	'cd0212':	['EQ', 'Tilt (stereo)'],
	'cc81':	['EQ', '10 Band Graphic (mono)'],
	'cc85':	['EQ', '10 Band Graphic (stereo)'],
	'cd0143':	['EQ', 'Cali Q Graphic (mono)'],
	'cd0144':	['EQ', 'Cali Q Graphic (stereo)'],
	'cd0244':	['EQ', 'Acoustic Sim (mono)'],
	'cd0245':	['EQ', 'Acoustic Sim (stereo)'],
	'cca3':	['Modulation', 'Optical Trem (mono)'],
	'ccb3':	['Modulation', 'Optical Trem (stereo)'],
	'cca2':	['Modulation', '60s Bias Trem (mono)'],
	'ccb2':	['Modulation', '60s Bias Trem (stereo)'],
	'cd0124':	['Modulation', 'Tremolo/Autopan (mono)'],
	'cd0125':	['Modulation', 'Tremolo/Autopan (stereo)'],
	'cd013e':	['Modulation', 'Harmonic Tremolo (mono)'],
	'cd013f':	['Modulation', 'Harmonic Tremolo (stereo)'],
	'cd0186':	['Modulation', 'Bleat Chop Trem (mono)'],
	'cd0187':	['Modulation', 'Bleat Chop Trem (stereo)'],
	'cc9f':	['Modulation', 'Script Mod Phase (mono)'],
	'ccab':	['Modulation', 'Script Mod Phase (stereo)'],
	'cd022f':	['Modulation', 'Pebble Phaser (mono)'],
	'cd0230':	['Modulation', 'Pebble Phaser (stereo)'],
	'cca0':	['Modulation', 'Ubiquitous Vibe (mono)'],
	'ccac':	['Modulation', 'Ubiquitous Vibe (stereo)'],
	'cd0126':	['Modulation', 'Deluxe Phaser (mono)'],
	'cd0127':	['Modulation', 'Deluxe Phaser (stereo)'],
	'cc9d':	['Modulation', 'Gray Flanger (mono)'],
	'cca9':	['Modulation', 'Gray Flanger (stereo)'],
	'cc9e':	['Modulation', 'Harmonic Flanger (mono)'],
	'ccaa':	['Modulation', 'Harmonic Flanger (stereo)'],
	'cc9c':	['Modulation', 'Courtesan Flange (mono)'],
	'cca8':	['Modulation', 'Courtesan Flange (stereo)'],
	'cd0130':	['Modulation', 'Dynamix Flanger (mono)'],
	'cd0131':	['Modulation', 'Dynamix Flanger (stereo)'],
	'cc9b':	['Modulation', 'Chorus (mono)'],
	'cca6':	['Modulation', 'Chorus (stereo)'],
	'cc9a':	['Modulation', '70s Chorus (mono)'],
	'cca5':	['Modulation', '70s Chorus (stereo)'],
	'cd0177':	['Modulation', 'PlastiChorus (mono)'],
	'cd0178':	['Modulation', 'PlastiChorus (stereo)'],
	'cca7':	['Modulation', 'Trinity Chorus  (stereo)'],
	'cca4':	['Modulation', 'Bubble Vibrato (mono)'],
	'ccb4':	['Modulation', 'Bubble Vibrato (stereo)'],
	'ccb1':	['Modulation', 'Vibe Rotary  (stereo)'],
	'ccaf':	['Modulation', '122 Rotary  (stereo)'],
	'ccb0':	['Modulation', '145 Rotary  (stereo)'],
	'cd0188':	['Modulation', 'Double Take Mono, Stereo Line 6 Original (mono)'],
	'cd0189':	['Modulation', 'Double Take Mono, Stereo Line 6 Original (stereo)'],
	'cd0240':	['Modulation', 'Poly Detune Mono Line 6 Original (mono)'],
	'cca1':	['Modulation', 'AM Ring Mod Mono, Stereo Line 6 Original (mono)'],
	'ccad':	['Modulation', 'AM Ring Mod Mono, Stereo Line 6 Original (stereo)'],
	'ccae':	['Modulation', 'Pitch Ring Mod  (stereo)'],
	'cd01d2':	['Modulation', 'Pattern Tremolo Legacy Line 6 Original  (legacy)'],
	'cd01d1':	['Modulation', 'Panner Legacy Line 6 Original  (legacy)'],
	'cd01ca':	['Modulation', 'Bias Tremolo Legacy 1960 Vox AC-15 Tremolo  (legacy)'],
	'cd01cf':	['Modulation', 'Opto Tremolo Legacy 1964 Fender Deluxe Reverb  (legacy)'],
	'cd01d8':	['Modulation', 'Panned Phaser Legacy Ibanez Flying Pan  (legacy)'],
	'cd01d0':	['Modulation', 'Barberpole Legacy Line 6 Original  (legacy)'],
	'cd01c9':	['Modulation', 'Dual Phaser Legacy Mu-Tron Bi-Phase  (legacy)'],
	'cd01cc':	['Modulation', 'U-Vibe Legacy Shin-ei Uni-Vibe  (legacy)'],
	'cd01da':	['Modulation', 'Phaser Legacy MXR Phase 90  (legacy)'],
	'cd01d3':	['Modulation', 'Pitch Vibrato Legacy BOSS VB-2  (legacy)'],
	'cd01d4':	['Modulation', 'Dimension Legacy Roland Dimension D  (legacy)'],
	'cd01cb':	['Modulation', 'Analog Chorus Legacy BOSS CE-1  (legacy)'],
	'cd01c7':	['Modulation', 'Tri Chorus Legacy Dytronics Tri-Stereo Chorus  (legacy)'],
	'cd01d9':	['Modulation', 'Analog Flanger Legacy MXR Flanger  (legacy)'],
	'cd01c8':	['Modulation', 'Jet Flanger Legacy A/DA Flanger  (legacy)'],
	'cd01ce':	['Modulation', 'AC Flanger Legacy MXR Flanger  (legacy)'],
	'cd01c6':	['Modulation', '80A Flanger Legacy A/DA Flanger  (legacy)'],
	'cd01c5':	['Modulation', 'Frequency Shift Legacy Line 6 Original  (legacy)'],
	'cd01cd':	['Modulation', 'Ring Modulator Legacy Line 6 Original  (legacy)'],
	'cd01d5':	['Modulation', 'Rotary Drum Legacy Fender Vibratone  (legacy)'],
	'cd01d6':	['Modulation', 'Rotary Drum/Horn  (legacy)'],
	'50':	['Delay', 'Simple Delay Mono, Stereo Line 6 Original (mono)'],
	'5c':	['Delay', 'Simple Delay Mono, Stereo Line 6 Original (stereo)'],
	'4f':	['Delay', 'Mod/Chorus Echo Mono, Stereo Line 6 Original (mono)'],
	'58':	['Delay', 'Mod/Chorus Echo Mono, Stereo Line 6 Original (stereo)'],
	'cd011f':	['Delay', 'Dual Delay  (stereo)'],
	'59':	['Delay', 'Multitap 4  (stereo)'],
	'5a':	['Delay', 'Multitap 6  (stereo)'],
	'5b':	['Delay', 'Ping Pong  (stereo)'],
	'51':	['Delay', 'Sweep Echo Mono, Stereo Line 6 Original (mono)'],
	'5d':	['Delay', 'Sweep Echo Mono, Stereo Line 6 Original (stereo)'],
	'4d':	['Delay', 'Ducked Delay Mono, Stereo TC Electronic 2290 (mono)'],
	'55':	['Delay', 'Ducked Delay Mono, Stereo TC Electronic 2290 (stereo)'],
	'cd011d':	['Delay', 'Reverse Delay Mono, Stereo Line 6 Original (mono)'],
	'cd011e':	['Delay', 'Reverse Delay Mono, Stereo Line 6 Original (stereo)'],
	'cd014b':	['Delay', 'Vintage Digital Mono, Stereo Line 6 Original (mono)'],
	'cd014c':	['Delay', 'Vintage Digital Mono, Stereo Line 6 Original (stereo)'],
	'cd015b':	['Delay', 'Vintage Swell Mono, Stereo Line 6 Original (mono)'],
	'cd015c':	['Delay', 'Vintage Swell Mono, Stereo Line 6 Original (stereo)'],
	'cd014d':	['Delay', 'Pitch Echo Mono, Stereo Line 6 Original (mono)'],
	'cd014e':	['Delay', 'Pitch Echo Mono, Stereo Line 6 Original (stereo)'],
	'52':	['Delay', 'Transistor Tape Mono, Stereo Maestro Echoplex EP-3 (mono)'],
	'5e':	['Delay', 'Transistor Tape Mono, Stereo Maestro Echoplex EP-3 (stereo)'],
	'cd018a':	['Delay', 'Cosmos Echo Mono, Stereo Roland RE-201 Space Echo (mono)'],
	'cd018b':	['Delay', 'Cosmos Echo Mono, Stereo Roland RE-201 Space Echo (stereo)'],
	'57':	['Delay', 'Harmony Delay  (stereo)'],
	'4c':	['Delay', 'Bucket Brigade Mono, Stereo BOSS DM-2 (mono)'],
	'54':	['Delay', 'Bucket Brigade Mono, Stereo BOSS DM-2 (stereo)'],
	'4b':	['Delay', 'Adriatic Delay Mono, Stereo BOSS DM-2 w/ Adrian Mod (mono)'],
	'53':	['Delay', 'Adriatic Delay Mono, Stereo BOSS DM-2 w/ Adrian Mod (stereo)'],
	'cd0159':	['Delay', 'Adriatic Swell Mono, Stereo Line 6 Original (mono)'],
	'cd015a':	['Delay', 'Adriatic Swell Mono, Stereo Line 6 Original (stereo)'],
	'4e':	['Delay', 'Elephant Man Mono, Stereo Electro-Harmonix Deluxe Memory Man (mono)'],
	'56':	['Delay', 'Elephant Man Mono, Stereo Electro-Harmonix Deluxe Memory Man (stereo)'],
	'cd01e8':	['Delay', 'Multi Pass Mono, Stereo Line 6 Original (mono)'],
	'cd01e9':	['Delay', 'Multi Pass Mono, Stereo Line 6 Original (stereo)'],
	'cd0243':	['Delay', 'Poly Sustain Mono Line 6 Original (mono)'],
	'cd0238':	['Delay', 'Glitch Delay Mono, Stereo Line 6 Original (mono)'],
	'cd0239':	['Delay', 'Glitch Delay Mono, Stereo Line 6 Original (stereo)'],
	'cd0198':	['Delay', 'Ping Pong Legacy Line 6 Original (legacy)'],
	'cd0194':	['Delay', 'Dynamic Legacy TC Electronic 2290 (legacy)'],
	'cd019a':	['Delay', 'Stereo Legacy Line 6 Original (legacy)'],
	'cd0192':	['Delay', 'Digital Legacy Line 6 Original (legacy)'],
	'cd0193':	['Delay', 'Dig w/Mod Legacy Line 6 Original (legacy)'],
	'cd0199':	['Delay', 'Reverse Legacy Line 6 Original (legacy)'],
	'cd0196':	['Delay', 'Lo Res Legacy Line 6 Original (legacy)'],
	'cd019d':	['Delay', 'Tube Echo (legacy)'],
	'cd019c':	['Delay', 'Tape Echo (legacy)'],
	'cd019b':	['Delay', 'Sweep Echo (legacy)'],
	'cd0195':	['Delay', 'Echo Platter (legacy)'],
	'cd018f':	['Delay', 'Analog Echo (legacy)'],
	'cd0190':	['Delay', 'Analog w/Mod (legacy)'],
	'cd0191':	['Delay', 'Auto-Volume Echo (legacy)'],
	'cd0197':	['Delay', 'Multi-Head (legacy)'],
	'cd01ea':	['Reverb', 'Glitz (mono)'],
	'cd01eb':	['Reverb', 'Glitz (stereo)'],
	'cd01f0':	['Reverb', 'Ganymede (mono)'],
	'cd01ec':	['Reverb', 'Ganymede (stereo)'],
	'cd01f3':	['Reverb', 'Searchlights (mono)'],
	'cd01ed':	['Reverb', 'Searchlights (stereo)'],
	'cd01f1':	['Reverb', 'Plateaux (mono)'],
	'cd01f2':	['Reverb', 'Plateaux (stereo)'],
	'cd01ee':	['Reverb', 'Double Tank (mono)'],
	'cd01ef':	['Reverb', 'Double Tank (stereo)'],
	'ccf6':	['Reverb', 'Plate (legacy)'],
	'ccf7':	['Reverb', 'Room (legacy)'],
	'ccf0':	['Reverb', 'Chamber (legacy)'],
	'ccf3':	['Reverb', 'Hall (legacy)'],
	'ccf2':	['Reverb', 'Echo (legacy)'],
	'ccf9':	['Reverb', 'Tile (legacy)'],
	'ccef':	['Reverb', 'Cave (legacy)'],
	'ccf1':	['Reverb', 'Ducking (legacy)'],
	'ccf4':	['Reverb', 'Octo (legacy)'],
	'ccee':	['Reverb', '63 Spring (legacy)'],
	'ccf8':	['Reverb', 'Spring (legacy)'],
	'ccf5':	['Reverb', 'Particle Verb (legacy)'],
	'ccb6':	['Pitch/Synth', 'Pitch Wham (mono)'],
	'ccb8':	['Pitch/Synth', 'Pitch Wham (stereo)'],
	'ccb7':	['Pitch/Synth', 'Twin Harmony (mono)'],
	'ccb9':	['Pitch/Synth', 'Twin Harmony (stereo)'],
	'cd0128':	['Pitch/Synth', 'Simple Pitch (mono)'],
	'cd0129':	['Pitch/Synth', 'Simple Pitch (stereo)'],
	'cd012a':	['Pitch/Synth', 'Dual Pitch (mono)'],
	'cd012b':	['Pitch/Synth', 'Dual Pitch (stereo)'],
	'cd023d':	['Pitch/Synth', 'Poly Pitch (mono)'],
	'cd023f':	['Pitch/Synth', 'Poly Wham (mono)'],
	'cd023e':	['Pitch/Synth', 'Poly Capo (mono)'],
	'cd0242':	['Pitch/Synth', '12 String (mono)'],
	'cd0179':	['Pitch/Synth', '3 Note Generator (mono)'],
	'cd017a':	['Pitch/Synth', '3 Note Generator (stereo)'],
	'cd017b':	['Pitch/Synth', '4 OSC Generator (mono)'],
	'cd0175':	['Pitch/Synth', '4 OSC Generator (stereo)'],
	'cd019e':	['Pitch/Synth', 'Bass Octaver (legacy)'],
	'cd01db':	['Pitch/Synth', 'Smart Harmony (legacy)'],
	'cd01b9':	['Pitch/Synth', 'Octi Synth (legacy)'],
	'cd01be':	['Pitch/Synth', 'Synth O Matic (legacy)'],
	'cd01b5':	['Pitch/Synth', 'Attack Synth (legacy)'],
	'cd01bf':	['Pitch/Synth', 'Synth String (legacy)'],
	'cd01b7':	['Pitch/Synth', 'Growler (legacy)'],
	'cc89':	['Filter', 'Mutant Filter (mono)'],
	'cc8b':	['Filter', 'Mutant Filter (stereo)'],
	'cc8a':	['Filter', 'Mystery Filter (mono)'],
	'cc8c':	['Filter', 'Mystery Filter (stereo)'],
	'cd012c':	['Filter', 'Autofilter (mono)'],
	'cd012d':	['Filter', 'Autofilter (stereo)'],
	'cd0213':	['Filter', 'Asheville Pattrn (mono)'],
	'cd0214':	['Filter', 'Asheville Pattrn (stereo)'],
	'cd01c3':	['Filter', 'Voice Box (legacy)'],
	'cd01c4':	['Filter', 'V Tron (legacy)'],
	'cd01ba':	['Filter', 'Q Filter (legacy)'],
	'cd01bb':	['Filter', 'Seeker (legacy)'],
	'cd01b8':	['Filter', 'Obi Wah (legacy)'],
	'cd01c2':	['Filter', 'Tron Up (legacy)'],
	'cd01c1':	['Filter', 'Tron Down (legacy)'],
	'cd01c0':	['Filter', 'Throbber (legacy)'],
	'cd01bc':	['Filter', 'Slow Filter (legacy)'],
	'cd01bd':	['Filter', 'Spin Cycle (legacy)'],
	'cd01b6':	['Filter', 'Comet Trails (legacy)'],
	'cd0110':	['Wah', 'UK Wah 846 (mono)'],
	'cd011a':	['Wah', 'UK Wah 846 (stereo)'],
	'cd010e':	['Wah', 'Teardrop 310 (mono)'],
	'cd0118':	['Wah', 'Teardrop 310 (stereo)'],
	'cd010d':	['Wah', 'Fassel (mono)'],
	'cd0117':	['Wah', 'Fassel (stereo)'],
	'cd0112':	['Wah', 'Weeper (mono)'],
	'cd011c':	['Wah', 'Weeper (stereo)'],
	'cd010a':	['Wah', 'Chrome (mono)'],
	'cd0114':	['Wah', 'Chrome (stereo)'],
	'cd0109':	['Wah', 'Chrome Custom (mono)'],
	'cd0113':	['Wah', 'Chrome Custom (stereo)'],
	'cd010f':	['Wah', 'Throaty (mono)'],
	'cd0119':	['Wah', 'Throaty (stereo)'],
	'cd0111':	['Wah', 'Vetta Wah (mono)'],
	'cd011b':	['Wah', 'Vetta Wah (stereo)'],
	'cd010b':	['Wah', 'Colorful (mono)'],
	'cd0115':	['Wah', 'Colorful (stereo)'],
	'cd010c':	['Wah', 'Conductor (mono)'],
	'cd0116':	['Wah', 'Conductor (stereo)'],
	'cd0105':	['Vol/Pan', 'Volume Pedal  (mono)'],
	'cd0108':	['Vol/Pan', 'Volume Pedal  (stereo)'],
	'cd0104':	['Vol/Pan', 'Gain (mono)'],
	'cd0106':	['Vol/Pan', 'Gain (stereo)'],
	'cd0107':	['Vol/Pan', 'Pan (stereo)'],
	'cd018c':	['Vol/Pan', 'Stereo Width (stereo)'],
	'cd024c':	['Vol/Pan', 'Stereo Imager (stereo)'],
	'2c':	['Amp', 'WhoWatt 100 (mono)'],
	'23':	['Amp', 'Soup Pro (mono)'],
	'24':	['Amp', 'Stone Age 185 (mono)'],
	'cd018d':	['Amp', 'Voltage Queen (mono)'],
	'26':	['Amp', 'Tweed Blues Nrm (mono)'],
	'25':	['Amp', 'Tweed Blues Brt (mono)'],
	'cd021d':	['Amp', 'Fullerton Nrm (mono)'],
	'cd021b':	['Amp', 'Fullerton Brt (mono)'],
	'cd021c':	['Amp', 'Fullerton Jump (mono)'],
	'cd0217':	['Amp', 'GrammaticoLG Nrm (mono)'],
	'cd0215':	['Amp', 'GrammaticoLG Brt (mono)'],
	'cd0216':	['Amp', 'GrammaticoLG Jmp (mono)'],
	'2b':	['Amp', 'US Small Tweed (mono)'],
	'cd024f':	['Amp', 'US Princess (mono)'],
	'27':	['Amp', 'US Deluxe Nrm (mono)'],
	'28':	['Amp', 'US Deluxe Vib (mono)'],
	'29':	['Amp', 'US Double Nrm (mono)'],
	'2a':	['Amp', 'US Double Vib (mono)'],
	'1d':	['Amp', 'Mail Order Twin Guitar Silvertone 1484 (mono)'],
	'13':	['Amp', 'Divided Duo Guitar 13 JRT 9/15 (mono)'],
	'18':	['Amp', 'Interstate Zed Guitar Dr Z Route 66 (mono)'],
	'cd0180':	['Amp', 'Derailed Ingrid Guitar Trainwreck Circuits Express (mono)'],
	'19':	['Amp', 'Jazz Rivet 120 Guitar Roland JC-120 Jazz Chorus (mono)'],
	'14':	['Amp', 'Essex A15 Guitar Vox AC-15 (mono)'],
	'15':	['Amp', 'Essex A30 Guitar Vox AC-30 with top boost (mono)'],
	'08':	['Amp', 'A30 Fawn Nrm Guitar Vox AC-30 Fawn (normal channel) (mono)'],
	'07':	['Amp', 'A30 Fawn Brt Guitar Vox AC-30 Fawn (bright channel) (mono)'],
	'cd0132':	['Amp', 'Matchstick Ch1 Guitar Matchless DC30 (channel 1) (mono)'],
	'cd0133':	['Amp', 'Matchstick Ch2 Guitar Matchless DC30 (channel 2) (mono)'],
	'cd0134':	['Amp', 'Matchstick Jump Guitar Matchless DC30 (jumped) (mono)'],
	'1e':	['Amp', 'Mandarin 80 Guitar Orange OR80 (mono)'],
	'0c':	['Amp', 'Brit J45 Nrm Guitar Marshall JTM-45 (normal channel) (mono)'],
	'0b':	['Amp', 'Brit J45 Brt Guitar Marshall JTM-45 (bright channel) (mono)'],
	'cd01de':	['Amp', 'Brit Trem Nrm Guitar Marshall JTM-50 (normal channel) (mono)'],
	'cd01df':	['Amp', 'Brit Trem Brt Guitar Marshall JTM-50 (bright channel) (mono)'],
	'cd01e0':	['Amp', 'Brit Trem Jump Guitar Marshall JTM-50 (jumped) (mono)'],
	'11':	['Amp', 'Brit Plexi Nrm Guitar Marshall Super Lead 100 (normal channel) (mono)'],
	'0f':	['Amp', 'Brit Plexi Brt Guitar Marshall Super Lead 100 (bright channel) (mono)'],
	'10':	['Amp', 'Brit Plexi Jump Guitar Marshall Super Lead 100 (jumped) (mono)'],
	'0e':	['Amp', 'Brit P75 Nrm Guitar Park 75 (normal channel) (mono)'],
	'0d':	['Amp', 'Brit P75 Brt Guitar Park 75 (bright channel) (mono)'],
	'0a':	['Amp', 'Brit 2204 Guitar Marshall JCM-800 (mono)'],
	'cd0200':	['Amp', 'Placater Clean Guitar Friedman BE-100 (clean channel) (mono)'],
	'cd01f4':	['Amp', 'Placater Dirty Guitar Friedman BE-100 (BE/HBE channel) (mono)'],
	'cd01e4':	['Amp', 'Cartographer Guitar Ben Adrian Cartographer (mono)'],
	'16':	['Amp', 'German Mahadeva Guitar Bogner Shiva (mono)'],
	'17':	['Amp', 'German Ubersonic Guitar Bogner Ueberschall  (mono)'],
	'cd0202':	['Amp', 'Cali Texas Ch1 Guitar MESA/Boogie Lone Star (clean channel) (mono)'],
	'cd01f6':	['Amp', 'Cali Texas Ch2 Guitar MESA/Boogie Lone Star (drive channel) (mono)'],
	'cd0139':	['Amp', 'Cali IV Rhythm 1 Guitar MESA/Boogie Mark IV (channel I) (mono)'],
	'cd013a':	['Amp', 'Cali IV Rhythm 2 Guitar MESA/Boogie Mark IV (channel II) (mono)'],
	'cd0138':	['Amp', 'Cali IV Lead Guitar MESA/Boogie Mark IV (lead channel) (mono)'],
	'12':	['Amp', 'Cali Rectifire Guitar MESA/Boogie Dual Rectifier (mono)'],
	'cd014f':	['Amp', 'Archetype Clean Guitar Paul Reed Smith Archon (clean channel) (mono)'],
	'cd0150':	['Amp', 'Archetype Lead Guitar Paul Reed Smith Archon (lead channel) (mono)'],
	'09':	['Amp', 'ANGL Meteor Guitar ENGL Fireball 100 (mono)'],
	'20':	['Amp', 'Solo Lead Clean Guitar Soldano SLO-100 (clean channel) (mono)'],
	'21':	['Amp', 'Solo Lead Crunch Guitar Soldano SLO-100 (crunch channel) (mono)'],
	'22':	['Amp', 'Solo Lead OD Guitar Soldano SLO-100 (overdrive channel) (mono)'],
	'1f':	['Amp', 'PV Panama Guitar Peavey 5150 (mono)'],
	'cd0231':	['Amp', 'Revv Gen Purple Guitar Revv Generator 120 (purple/gain ch. 3) (mono)'],
	'cd0221':	['Amp', 'Revv Gen Red Guitar Revv Generator 120 (red/high gain ch. 4) (mono)'],
	'cd0259':	['Amp', 'Das Benzin Mega Guitar Diezel VH4 (mega chanel) (mono)'],
	'cd0257':	['Amp', 'Das Benzin Lead Guitar Diezel VH4 (lead chanel) (mono)'],
	'1b':	['Amp', 'Line 6 Elektrik Guitar Line 6 Original (mono)'],
	'1a':	['Amp', 'Line 6 Doom Guitar Line 6 Original (mono)'],
	'1c':	['Amp', 'Line 6 Epic Guitar Line 6 Original (mono)'],
	'cd0142':	['Amp', 'Line 6 2204 Mod Guitar Line 6 Original (mono)'],
	'cd0148':	['Amp', 'Line 6 Fatality Guitar Line 6 Original (mono)'],
	'cd0153':	['Amp', 'Line 6 Litigator Guitar Line 6 Original (mono)'],
	'cd015d':	['Amp', 'Line 6 Badonk Guitar Line 6 Original (mono)'],
	'06':	['Amp', 'Ampeg B-15NF Bass Ampeg B-15NF Portaflex (mono)'],
	'05':	['Amp', 'Ampeg SVT Nrm Bass Ampeg SVT (normal channel) (mono)'],
	'04':	['Amp', 'Ampeg SVT Brt Bass Ampeg SVT (bright channel) (mono)'],
	'cd0207':	['Amp', 'Ampeg SVT-4 PRO (mono)'],
	'cd015e':	['Amp', 'Woody Blue (mono)'],
	'cd01e6':	['Amp', 'Agua 51 (mono)'],
	'02':	['Amp', 'Cali Bass (mono)'],
	'00':	['Amp', 'Cali 400 Ch1 (mono)'],
	'01':	['Amp', 'Cali 400 Ch2 (mono)'],
	'03':	['Amp', 'G Cougar 800 (mono)'],
	'cd0157':	['Amp', 'Del Sol 300 (mono)'],
	'cd016b':	['Amp', 'Busy One Ch1 (mono)'],
	'cd016c':	['Amp', 'Busy One Ch2 (mono)'],
	'cd016d':	['Amp', 'Busy One Jump (mono)'],
	'cce7':	['Amp', 'Studio Tube Pre (mono)'],
	'cce6':	['Preamp', 'WhoWatt 100 (mono)'],
	'ccdd':	['Preamp', 'Soup Pro (mono)'],
	'ccde':	['Preamp', 'Stone Age 185 (mono)'],
	'cd018e':	['Preamp', 'Voltage Queen (mono)'],
	'cce0':	['Preamp', 'Tweed Blues Nrm (mono)'],
	'ccdf':	['Preamp', 'Tweed Blues Brt (mono)'],
	'cd0220':	['Preamp', 'Fullerton Nrm (mono)'],
	'cd021e':	['Preamp', 'Fullerton Brt (mono)'],
	'cd021f':	['Preamp', 'Fullerton Jump (mono)'],
	'cd021a':	['Preamp', 'GrammaticoLG Nrm (mono)'],
	'cd0218':	['Preamp', 'GrammaticoLG Brt (mono)'],
	'cd0219':	['Preamp', 'GrammaticoLG Jmp (mono)'],
	'cce5':	['Preamp', 'US Small Tweed (mono)'],
	'cd0250':	['Preamp', 'US Princess (mono)'],
	'cce1':	['Preamp', 'US Deluxe Nrm (mono)'],
	'cce2':	['Preamp', 'US Deluxe Vib (mono)'],
	'cce3':	['Preamp', 'US Double Nrm (mono)'],
	'cce4':	['Preamp', 'US Double Vib (mono)'],
	'ccd7':	['Preamp', 'Mail Order Twin Guitar Silvertone 1484 (mono)'],
	'cccd':	['Preamp', 'Divided Duo Guitar 13 JRT 9/15 (mono)'],
	'ccd2':	['Preamp', 'Interstate Zed Guitar Dr Z Route 66 (mono)'],
	'cd0181':	['Preamp', 'Derailed Ingrid Guitar Trainwreck Circuits Express (mono)'],
	'ccd3':	['Preamp', 'Jazz Rivet 120 Guitar Roland JC-120 Jazz Chorus (mono)'],
	'ccce':	['Preamp', 'Essex A15 Guitar Vox AC-15 (mono)'],
	'cccf':	['Preamp', 'Essex A30 Guitar Vox AC-30 with top boost (mono)'],
	'ccc2':	['Preamp', 'A30 Fawn Nrm Guitar Vox AC-30 Fawn (normal channel) (mono)'],
	'ccc1':	['Preamp', 'A30 Fawn Brt Guitar Vox AC-30 Fawn (bright channel) (mono)'],
	'cd0135':	['Preamp', 'Matchstick Ch1 Guitar Matchless DC30 (channel 1) (mono)'],
	'cd0136':	['Preamp', 'Matchstick Ch2 Guitar Matchless DC30 (channel 2) (mono)'],
	'cd0137':	['Preamp', 'Matchstick Jump Guitar Matchless DC30 (jumped) (mono)'],
	'ccd8':	['Preamp', 'Mandarin 80 Guitar Orange OR80 (mono)'],
	'ccc6':	['Preamp', 'Brit J45 Nrm Guitar Marshall JTM-45 (normal channel) (mono)'],
	'ccc5':	['Preamp', 'Brit J45 Brt Guitar Marshall JTM-45 (bright channel) (mono)'],
	'cd01e1':	['Preamp', 'Brit Trem Nrm Guitar Marshall JTM-50 (normal channel) (mono)'],
	'cd01e2':	['Preamp', 'Brit Trem Brt Guitar Marshall JTM-50 (bright channel) (mono)'],
	'cd01e3':	['Preamp', 'Brit Trem Jump Guitar Marshall JTM-50 (jumped) (mono)'],
	'cccb':	['Preamp', 'Brit Plexi Nrm Guitar Marshall Super Lead 100 (normal channel) (mono)'],
	'ccc9':	['Preamp', 'Brit Plexi Brt Guitar Marshall Super Lead 100 (bright channel) (mono)'],
	'ccca':	['Preamp', 'Brit Plexi Jump Guitar Marshall Super Lead 100 (jumped) (mono)'],
	'ccc8':	['Preamp', 'Brit P75 Nrm Guitar Park 75 (normal channel) (mono)'],
	'ccc7':	['Preamp', 'Brit P75 Brt Guitar Park 75 (bright channel) (mono)'],
	'ccc4':	['Preamp', 'Brit 2204 Guitar Marshall JCM-800 (mono)'],
	'cd0201':	['Preamp', 'Placater Clean Guitar Friedman BE-100 (clean channel) (mono)'],
	'cd01f5':	['Preamp', 'Placater Dirty Guitar Friedman BE-100 (BE/HBE channel) (mono)'],
	'cd01e5':	['Preamp', 'Cartographer Guitar Ben Adrian Cartographer (mono)'],
	'ccd0':	['Preamp', 'German Mahadeva Guitar Bogner Shiva (mono)'],
	'ccd1':	['Preamp', 'German Ubersonic Guitar Bogner Ueberschall  (mono)'],
	'cd0203':	['Preamp', 'Cali Texas Ch1 Guitar MESA/Boogie Lone Star (clean channel) (mono)'],
	'cd01f7':	['Preamp', 'Cali Texas Ch2 Guitar MESA/Boogie Lone Star (drive channel) (mono)'],
	'cd013c':	['Preamp', 'Cali IV Rhythm 1 Guitar MESA/Boogie Mark IV (channel I) (mono)'],
	'cd013d':	['Preamp', 'Cali IV Rhythm 2 Guitar MESA/Boogie Mark IV (channel II) (mono)'],
	'cd013b':	['Preamp', 'Cali IV Lead Guitar MESA/Boogie Mark IV (lead channel) (mono)'],
	'cccc':	['Preamp', 'Cali Rectifire Guitar MESA/Boogie Dual Rectifier (mono)'],
	'cd0151':	['Preamp', 'Archetype Clean Guitar Paul Reed Smith Archon (clean channel) (mono)'],
	'cd0152':	['Preamp', 'Archetype Lead Guitar Paul Reed Smith Archon (lead channel) (mono)'],
	'ccc3':	['Preamp', 'ANGL Meteor Guitar ENGL Fireball 100 (mono)'],
	'ccda':	['Preamp', 'Solo Lead Clean Guitar Soldano SLO-100 (clean channel) (mono)'],
	'ccdb':	['Preamp', 'Solo Lead Crunch Guitar Soldano SLO-100 (crunch channel) (mono)'],
	'ccdc':	['Preamp', 'Solo Lead OD Guitar Soldano SLO-100 (overdrive channel) (mono)'],
	'ccd9':	['Preamp', 'PV Panama Guitar Peavey 5150 (mono)'],
	'cd0232':	['Preamp', 'Revv Gen Purple Guitar Revv Generator 120 (purple/gain ch. 3) (mono)'],
	'cd0222':	['Preamp', 'Revv Gen Red Guitar Revv Generator 120 (red/high gain ch. 4) (mono)'],
	'cd025a':	['Preamp', 'Das Benzin Mega Guitar Diezel VH4 (mega chanel) (mono)'],
	'cd0258':	['Preamp', 'Das Benzin Lead Guitar Diezel VH4 (lead chanel) (mono)'],
	'ccd5':	['Preamp', 'Line 6 Elektrik Guitar Line 6 Original (mono)'],
	'ccd4':	['Preamp', 'Line 6 Doom Guitar Line 6 Original (mono)'],
	'ccd6':	['Preamp', 'Line 6 Epic Guitar Line 6 Original (mono)'],
	'cd014a':	['Preamp', 'Line 6 2204 Mod Guitar Line 6 Original (mono)'],
	'cd0149':	['Preamp', 'Line 6 Fatality Guitar Line 6 Original (mono)'],
	'cd0156':	['Preamp', 'Line 6 Litigator Guitar Line 6 Original (mono)'],
	'cd0162':	['Preamp', 'Line 6 Badonk Guitar Line 6 Original (mono)'],
	'ccc0':	['Preamp', 'Ampeg B-15NF Bass Ampeg B-15NF Portaflex (mono)'],
	'ccbf':	['Preamp', 'Ampeg SVT Nrm Bass Ampeg SVT (normal channel) (mono)'],
	'ccbe':	['Preamp', 'Ampeg SVT Brt Bass Ampeg SVT (bright channel) (mono)'],
	'cd0208':	['Preamp', 'Ampeg SVT-4 PRO (mono)'],
	'cd0161':	['Preamp', 'Woody Blue (mono)'],
	'cd01e7':	['Preamp', 'Agua 51 (mono)'],
	'ccbc':	['Preamp', 'Cali Bass (mono)'],
	'ccba':	['Preamp', 'Cali 400 Ch1 (mono)'],
	'ccbb':	['Preamp', 'Cali 400 Ch2 (mono)'],
	'ccbd':	['Preamp', 'G Cougar 800 (mono)'],
	'cd0158':	['Preamp', 'Del Sol 300 (mono)'],
	'cd0172':	['Preamp', 'Busy One Ch1 (mono)'],
	'cd0173':	['Preamp', 'Busy One Ch2 (mono)'],
	'cd0174':	['Preamp', 'Busy One Jump (mono)'],
	'2c1a47':	['Amp+Cab', 'WhoWatt 100  (mono)'],
	'231a33':	['Amp+Cab', 'Soup Pro  (mono)'],
	'241a2f':	['Amp+Cab', 'Stone Age 185  (mono)'],
	'cd018d1a31':	['Amp+Cab', 'Voltage Queen  (mono)'],
	'261a3d':	['Amp+Cab', 'Tweed Blues Nrm  (mono)'],
	'251a3d':	['Amp+Cab', 'Tweed Blues Brt  (mono)'],
	'cd021d1acd0227':	['Amp+Cab', 'Fullerton Nrm  (mono)'],
	'cd021b1acd0227':	['Amp+Cab', 'Fullerton Brt  (mono)'],
	'cd021c1acd0227':	['Amp+Cab', 'Fullerton Jump  (mono)'],
	'cd02171acd0228':	['Amp+Cab', 'GrammaticoLG Nrm (mono)'],
	'cd02151acd0228':	['Amp+Cab', 'GrammaticoLG Brt (mono)'],
	'cd02161acd0228':	['Amp+Cab', 'GrammaticoLG Jmp (mono)'],
	'2b1a34':	['Amp+Cab', 'US Small Tweed  (mono)'],
	'cd024f1acd024d':	['Amp+Cab', 'US Princess  (mono)'],
	'271a31':	['Amp+Cab', 'US Deluxe Nrm  (mono)'],
	'281a31':	['Amp+Cab', 'US Deluxe Vib  (mono)'],
	'291a36':	['Amp+Cab', 'US Double Nrm  (mono)'],
	'2a1a36':	['Amp+Cab', 'US Double Vib  (mono)'],
	'1d1a39':	['Amp+Cab', 'Mail Order Twin Guitar Silvertone 1484  (mono)'],
	'131a2e':	['Amp+Cab', 'Divided Duo Guitar 13 JRT 9/15  (mono)'],
	'181a37':	['Amp+Cab', 'Interstate Zed Guitar Dr Z Route 66  (mono)'],
	'cd01801a40':	['Amp+Cab', 'Derailed Ingrid Guitar Trainwreck Circuits Express  (mono)'],
	'191a38':	['Amp+Cab', 'Jazz Rivet 120 Guitar Roland JC-120 Jazz Chorus  (mono)'],
	'141a2d':	['Amp+Cab', 'Essex A15 Guitar Vox AC-15  (mono)'],
	'151a3a':	['Amp+Cab', 'Essex A30 Guitar Vox AC-30 with top boost  (mono)'],
	'081a35':	['Amp+Cab', 'A30 Fawn Nrm Guitar Vox AC-30 Fawn (normal channel)  (mono)'],
	'071a35':	['Amp+Cab', 'A30 Fawn Brt Guitar Vox AC-30 Fawn (bright channel)  (mono)'],
	'cd01321acd0167':	['Amp+Cab', 'Matchstick Ch1 Guitar Matchless DC30 (channel 1)  (mono)'],
	'cd01331acd0166':	['Amp+Cab', 'Matchstick Ch2 Guitar Matchless DC30 (channel 2)  (mono)'],
	'cd01341acd0166':	['Amp+Cab', 'Matchstick Jump Guitar Matchless DC30 (jumped)  (mono)'],
	'1e1a43':	['Amp+Cab', 'Mandarin 80 Guitar Orange OR80  (mono)'],
	'0c1a41':	['Amp+Cab', 'Brit J45 Nrm Guitar Marshall JTM-45 (normal channel)  (mono)'],
	'0b1a41':	['Amp+Cab', 'Brit J45 Brt Guitar Marshall JTM-45 (bright channel)  (mono)'],
	'cd01de1a42':	['Amp+Cab', 'Brit Trem Nrm Guitar Marshall JTM-50 (normal channel)  (mono)'],
	'cd01df1a42':	['Amp+Cab', 'Brit Trem Brt Guitar Marshall JTM-50 (bright channel)  (mono)'],
	'cd01e01a42':	['Amp+Cab', 'Brit Trem Jump Guitar Marshall JTM-50 (jumped)  (mono)'],
	'111a42':	['Amp+Cab', 'Brit Plexi Nrm Guitar Marshall Super Lead 100 (normal channel)  (mono)'],
	'0f1a42':	['Amp+Cab', 'Brit Plexi Brt Guitar Marshall Super Lead 100 (bright channel)  (mono)'],
	'101a42':	['Amp+Cab', 'Brit Plexi Jump Guitar Marshall Super Lead 100 (jumped)  (mono)'],
	'0e1a3f':	['Amp+Cab', 'Brit P75 Nrm Guitar Park 75 (normal channel)  (mono)'],
	'0d1a3f':	['Amp+Cab', 'Brit P75 Brt Guitar Park 75 (bright channel)  (mono)'],
	'0a1a3f':	['Amp+Cab', 'Brit 2204 Guitar Marshall JCM-800  (mono)'],
	'cd02001a40':	['Amp+Cab', 'Placater Clean Guitar Friedman BE-100 (clean channel)  (mono)'],
	'cd01f41a40':	['Amp+Cab', 'Placater Dirty Guitar Friedman BE-100 (BE/HBE channel)  (mono)'],
	'cd01e41a46':	['Amp+Cab', 'Cartographer Guitar Ben Adrian Cartographer  (mono)'],
	'161a30':	['Amp+Cab', 'German Mahadeva Guitar Bogner Shiva  (mono)'],
	'171a46':	['Amp+Cab', 'German Ubersonic Guitar Bogner Ueberschall  (mono)'],
	'cd02021a37':	['Amp+Cab', 'Cali Texas Ch1 Guitar MESA/Boogie Lone Star (clean channel)  (mono)'],
	'cd01f61a37':	['Amp+Cab', 'Cali Texas Ch2 Guitar MESA/Boogie Lone Star (drive channel)  (mono)'],
	'cd01391acd0164':	['Amp+Cab', 'Cali IV Rhythm 1 Guitar MESA/Boogie Mark IV (channel I)  (mono)'],
	'cd013a1acd0164':	['Amp+Cab', 'Cali IV Rhythm 2 Guitar MESA/Boogie Mark IV (channel II)  (mono)'],
	'cd01381a40':	['Amp+Cab', 'Cali IV Lead Guitar MESA/Boogie Mark IV (lead channel)  (mono)'],
	'121a40':	['Amp+Cab', 'Cali Rectifire Guitar MESA/Boogie Dual Rectifier  (mono)'],
	'cd014f1a40':	['Amp+Cab', 'Archetype Clean Guitar Paul Reed Smith Archon (clean channel)  (mono)'],
	'cd01501a40':	['Amp+Cab', 'Archetype Lead Guitar Paul Reed Smith Archon (lead channel)  (mono)'],
	'091a48':	['Amp+Cab', 'ANGL Meteor Guitar ENGL Fireball 100  (mono)'],
	'201a44':	['Amp+Cab', 'Solo Lead Clean Guitar Soldano SLO-100 (clean channel)  (mono)'],
	'211a44':	['Amp+Cab', 'Solo Lead Crunch Guitar Soldano SLO-100 (crunch channel)  (mono)'],
	'221a44':	['Amp+Cab', 'Solo Lead OD Guitar Soldano SLO-100 (overdrive channel)  (mono)'],
	'1f1a40':	['Amp+Cab', 'PV Panama Guitar Peavey 5150  (mono)'],
	'cd02311a40':	['Amp+Cab', 'Revv Gen Purple Guitar Revv Generator 120 (purple/gain ch. 3)  (mono)'],
	'cd02211a40':	['Amp+Cab', 'Revv Gen Red Guitar Revv Generator 120 (red/high gain ch. 4)  (mono)'],
	'cd02591a40':	['Amp+Cab', 'Das Benzin Mega Guitar Diezel VH4 (mega chanel)  (mono)'],
	'cd02571a40':	['Amp+Cab', 'Das Benzin Lead Guitar Diezel VH4 (lead chanel)  (mono)'],
	'1b1a3e':	['Amp+Cab', 'Line 6 Elektrik Guitar Line 6 Original  (mono)'],
	'1a1a47':	['Amp+Cab', 'Line 6 Doom Guitar Line 6 Original  (mono)'],
	'1c1a40':	['Amp+Cab', 'Line 6 Epic Guitar Line 6 Original  (mono)'],
	'cd01421a40':	['Amp+Cab', 'Line 6 2204 Mod Guitar Line 6 Original  (mono)'],
	'cd01481a40':	['Amp+Cab', 'Line 6 Fatality Guitar Line 6 Original  (mono)'],
	'cd01531a31':	['Amp+Cab', 'Line 6 Litigator Guitar Line 6 Original  (mono)'],
	'cd015d1a40':	['Amp+Cab', 'Line 6 Badonk Guitar Line 6 Original  (mono)'],
	'061a32':	['Amp+Cab', 'Ampeg B-15NF Bass Ampeg B-15NF Portaflex  (mono)'],
	'051a4a':	['Amp+Cab', 'Ampeg SVT Nrm Bass Ampeg SVT (normal channel)  (mono)'],
	'041a4a':	['Amp+Cab', 'Ampeg SVT Brt Bass Ampeg SVT (bright channel)  (mono)'],
	'cd02071a4a':	['Amp+Cab', 'Ampeg SVT-4 PRO  (mono)'],
	'cd015e1acd016e':	['Amp+Cab', 'Woody Blue  (mono)'],
	'cd01e61a3b':	['Amp+Cab', 'Agua 51  (mono)'],
	'021a49':	['Amp+Cab', 'Cali Bass  (mono)'],
	'001a3b':	['Amp+Cab', 'Cali 400 Ch1  (mono)'],
	'011a3b':	['Amp+Cab', 'Cali 400 Ch2  (mono)'],
	'031a3c':	['Amp+Cab', 'G Cougar 800  (mono)'],
	'cd01571acd0165':	['Amp+Cab', 'Del Sol 300  (mono)'],
	'cd016b1a4a':	['Amp+Cab', 'Busy One Ch1  (mono)'],
	'cd016c1a4a':	['Amp+Cab', 'Busy One Ch2  (mono)'],
	'cd016d1a4a':	['Amp+Cab', 'Busy One Jump  (mono)'],
	'ccfa':	['Send/Return', 'Send/Return (mono)'],
	'ccfb':	['Send/Return', 'Send L (mono)'],
	'cce8':	['Send/Return', 'Send R (mono)'],
	'cce9':	['Send/Return', 'Return L (mono)'],
	'cc8d':	['Send/Return', 'Return R (mono)'],
	'cc8e':	['Send/Return', 'FX Loop L (mono)'],
	'ccfe':	['Send/Return', 'FX Loop R (stereo)'],
	'ccec':	['Send/Return', 'Send L/R (stereo)'],
	'cc91':	['Send/Return', 'Return L/R (stereo)'],
	'33':	['Cab', 'Soup Pro Ellipse Single, Dual 1 x 6x9" Supro S6616 (mono)'],
	'34':	['Cab', '1x8 Small Tweed Single, Dual 1x8" Fender Champ (mono)'],
	'cd024d':	['Cab', '1x10 US Princess Single, Dual 1x10" Fender Princeton Reverb (mono)'],
	'2f':	['Cab', '1x12 Field Coil Single, Dual 1x12" Gibson EH185 (mono)'],
	'cd0227':	['Cab', '1x12 Fullerton Single, Dual 1x12" Fender 5C3 Tweed Deluxe (mono)'],
	'cd0228':	['Cab', '1x12 Grammatico Single, Dual 1x12" Grammatico LaGrange (mono)'],
	'31':	['Cab', '1x12 US Deluxe Single, Dual 1x12" Fender Deluxe Oxford (mono)'],
	'cd024e':	['Cab', '1x12 US Princess Single, Dual 1x12" Fender Princeton Reverb (mono)'],
	'2e':	['Cab', '1x12 Celest 12H Single, Dual 1x12" 13 JRT 9/15 G12 H30 (mono)'],
	'2d':	['Cab', '1x12 Blue Bell Single, Dual 1x12" Vox AC-15 Blue (mono)'],
	'30':	['Cab', '1x12 Lead 80 Single, Dual 1x12" Bogner Shiva CL80 (mono)'],
	'cd0164':	['Cab', '1x12 Cali IV Single, Dual 1x12" MESA/Boogie Mk IV (mono)'],
	'cd0163':	['Cab', '1x12 Cali Ext Single, Dual 1x12" MESA/Boogie EVM12L (mono)'],
	'36':	['Cab', '2x12 Double C12N Single, Dual 2x12" Fender Twin C12N (mono)'],
	'39':	['Cab', '2x12 Mail C12Q Single, Dual 2x12" Silvertone 1484 (mono)'],
	'37':	['Cab', '2x12 Interstate Single, Dual 2x12" Dr Z Z Best V30 (mono)'],
	'38':	['Cab', '2x12 Jazz Rivet Single, Dual 2x12" Roland JC-120 (mono)'],
	'3a':	['Cab', '2x12 Silver Bell Single, Dual 2x12" Vox AC-30TB Silver (mono)'],
	'35':	['Cab', '2x12 Blue Bell Single, Dual 2x12" Vox AC-30 Fawn Blue (mono)'],
	'cd0167':	['Cab', '2x12 Match H30 Single, Dual 1x12" Matchless DC-30 G12H30 (mono)'],
	'cd0166':	['Cab', '2x12 Match G25 Single, Dual 1x12" Matchless DC-30 Greenback 25 (mono)'],
	'3d':	['Cab', '4x10 Tweed P10R Single, Dual 4x10" Fender Bassman P10R (mono)'],
	'47':	['Cab', '4x12 WhoWatt 100 Single, Dual 4x12" Hiwatt AP Fane (mono)'],
	'43':	['Cab', '4x12 Mandarin EM Single, Dual 4x12" Orange Eminence (mono)'],
	'42':	['Cab', '4x12 Greenback25 Single, Dual 4x12" Marshall Basketweave G12 M25 (mono)'],
	'41':	['Cab', '4x12 Greenback20 Single, Dual 4x12" Marshall Basketweave G12 M20 (mono)'],
	'3f':	['Cab', '4x12 Blackback30 Single, Dual 4x12" Park 75 G12 H30 (mono)'],
	'3e':	['Cab', '4x12 1960 T75 Single, Dual 4x12" Marshall 1960 AT75 (mono)'],
	'46':	['Cab', '4x12 Uber V30 Single, Dual 4x12" Bogner Uberkab V30 (mono)'],
	'45':	['Cab', '4x12 Uber T75 Single, Dual 4x12" Bogner Uberkab T75 (mono)'],
	'40':	['Cab', '4x12 Cali V30 (mono)'],
	'48':	['Cab', '4x12 XXL V30 (mono)'],
	'44':	['Cab', '4x12 SoloLead EM  (mono)'],
	'cd0165':	['Cab', '1x12 Del Sol (mono)'],
	'32':	['Cab', '1x15 Ampeg B-15  (mono)'],
	'cd0168':	['Cab', '1x18 Del Sol (mono)'],
	'cd016e':	['Cab', '1x18 Woody Blue  (mono)'],
	'3b':	['Cab', '2x15 Brute (mono)'],
	'3c':	['Cab', '4x10 Ampeg HLF  (mono)'],
	'49':	['Cab', '6x10 Cali Power  (mono)'],
	'4a':	['Cab', '8x10 Ampeg SVT E (mono)'],
	'cc95':	['Impulse Response', '1024 samples'],
	'cc96':	['Impulse Response', '2048 samples'],
}
